I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 138, in script
  File "game/script.rpy", line 138, in python
NameError: name 'circleirisout' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "C:\Documents and Settings\Andy Bogard\Desktop\renpy-6.15.7-sdk\renpy\execution.py", line 288, in run
    node.execute()
  File "C:\Documents and Settings\Andy Bogard\Desktop\renpy-6.15.7-sdk\renpy\ast.py", line 1106, in execute
    paired = renpy.python.py_eval(self.paired)
  File "C:\Documents and Settings\Andy Bogard\Desktop\renpy-6.15.7-sdk\renpy\python.py", line 1331, in py_eval
    return eval(py_compile(source, 'eval'), globals, locals)
  File "game/script.rpy", line 138, in <module>
    scene bg park with circleirisout
NameError: name 'circleirisout' is not defined

Windows-XP-5.1.2600-SP3
Ren'Py 6.15.7.374
Softboiled Detective Story 0.001
